<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>  <!-- rebuild -->


    <artifactId>quality_server_shared_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
    <parent>
        <artifactId>quality_root_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
        <groupId>com.sparkutils</groupId>
        <version>${revision}</version>
    </parent>

    <version>${revision}</version>
    <name>Quality Shared Server Components</name>
    <description>Common class files for both Server/Classic usage and test classes via Connect api</description>

    <dependencies>
        <dependency>
            <groupId>com.sparkutils</groupId>
            <artifactId>quality_api_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${revision}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sparkutils</groupId>
                    <artifactId>quality_api_stub_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scalaCompatVersion}</artifactId>
            <version>${sparkVersion}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
