@startmindmap

* Rule Suite - Id(1, 1) 
 *_ ruleSetResults
  * Rule Set - Id(2, 1)
   *_ ruleResults
    * Rule - Id(3, 3)
     *_ ruleResult - {key: 5435, value: RESULT2}
    * Rule - Id(4, 2)
     *_ ruleResult - {key: 32498, value: RESULT1}
  * Rule Set - Id(3, 2)
   *_ ruleResults
    * Rule - Id(5, 1)
     *_ ruleResult - {key: 12550, value: RESULT4}
    * Rule - Id(6, 1)
     *_ ruleResult - {key: 79835, value: RESULT6}

@endmindmap