name: Maven with Spark
description: Combines mvn and spark
inputs:
  title:
    required: true
    description: step title
  script:
    required: true
    description: script to run for step
  gpgKey:
    required: false
    default: ""
    description: needed for publish

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: vemonet/setup-spark@v1.2.0
      with:
        spark-version: '3.2.1'
        hadoop-version: '3.2'
        scala-version: '2.13'
        spark-url: 'https://archive.apache.org/dist/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2-scala2.13.tgz'
    - name: Set up JDK 8
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven #this caches ~/.m2/repo
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: OSSRH_USERNAME # env variable for username in deploy
        server-password: OSSRH_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ inputs.gpgKey }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
    - name: ${{ inputs.title }}
      run: ${{ inputs.script }}
      shell: bash