@startmindmap

* Rule Suite - Id(1, 1) 
 *_ ruleSetResults
  * Rule Set - Id(2, 1)
   *_ ruleResults
    * Rule - Id(3, 3)
     *_ ruleResult - '124'\\n
     *_ resultDDL - BIGINT
    * Rule - Id(4, 2)
     *_ ruleResult - {key: 5435, value: RESULT}
     *_ resultDDL - STRUCT<key: INT, value: STRING>
  * Rule Set - Id(3, 2)
   *_ ruleResults
    * Rule - Id(5, 1)
     *_ ruleResult - 'A Result'\\n
     *_ resultDDL - STRING
    * Rule - Id(6, 1)
     *_ ruleResult - '4304140.23414000'\\n
     *_ resultDDL - DECIMAL(20,18)

@endmindmap