@startmindmap

<style>
mindmapDiagram {
  .passed {
    BackgroundColor lightgreen
  }
  .failed {
    BackgroundColor #FFBBCC
  }
  .softfailed {
    BackgroundColor lightblue
  }
}
</style>
* Rule Suite - Id(1, 1) 
 * overallResult == failed <<failed>>
 *_ ruleSetResults
  * Rule Set - Id(2, 1)
   * overallResult == failed <<failed>>
   *_ ruleResults
    * Rule - Id(3, 3) - failed <<failed>>
    * Rule - Id(4, 2) - soft failed <<softfailed>>
  * Rule Set - Id(3, 2)
   * overallResult ==  passed <<passed>>
   *_ ruleResults
    * Rule - Id(5, 1) - soft failed <<softfailed>>
    * Rule - Id(6, 1) - passed <<passed>>

@endmindmap