<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>  <!-- rebuild -->


    <artifactId>quality_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
    <parent>
        <artifactId>quality_root_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
        <groupId>com.sparkutils</groupId>
        <version>${revision}</version>
    </parent>

    <version>${revision}</version>
    <name>Quality</name>
    <description>A Spark library for managing in-process data quality rules via Spark SQL</description>

    <profiles>
        <profile>
            <id>Spark4</id>
            <dependencies>
                <!-- actual client code needed to connect is passed via spark.api -->
                <!-- shared test code - Probably shouldn't need it -->
                <dependency>
                    <groupId>org.apache.spark</groupId>
                    <artifactId>spark-connect-client-jvm_${scalaCompatVersion}</artifactId>
                    <version>${sparkVersion}</version>
                    <classifier>tests</classifier>
                    <scope>test</scope>
                </dependency>
                <!-- actual server to spawn for testing -->
                <dependency>
                    <groupId>org.apache.spark</groupId>
                    <artifactId>spark-connect_${scalaCompatVersion}</artifactId>
                    <version>${sparkVersion}</version>
                    <scope>test</scope>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>Spark41</id>
            <dependencies>
                <!-- actual client code needed to connect is passed via spark.api -->
                <!-- shared test code - Probably shouldn't need it -->
                <dependency>
                    <groupId>org.apache.spark</groupId>
                    <artifactId>spark-connect-client-jvm_${scalaCompatVersion}</artifactId>
                    <version>${sparkVersion}</version>
                    <classifier>tests</classifier>
                    <scope>test</scope>
                </dependency>
                <!-- actual server to spawn for testing -->
                <dependency>
                    <groupId>org.apache.spark</groupId>
                    <artifactId>spark-connect_${scalaCompatVersion}</artifactId>
                    <version>${sparkVersion}</version>
                    <scope>test</scope>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
    <properties>
        <!-- need the api as well for docs building -->
        <server_api_docs_dir>../api/src/main/scala</server_api_docs_dir>
        <server_api_docs_encoding_dir>../api/src/main/${encodingDir}</server_api_docs_encoding_dir>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.sparkutils</groupId>
            <artifactId>shim_compilation_${shimCompilationRuntime}_${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${shimCompilationVersion}</version>
            <scope>provided</scope>
            <classifier>sources</classifier>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.spark</groupId>
                    <artifactId>spark-sql_${scalaCompatVersion}</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.sparkutils</groupId>
            <artifactId>shim_runtime_${shimRuntime}_${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${shimRuntimeVersion}</version>
        </dependency>
        <dependency>
            <groupId>com.sparkutils</groupId>
            <artifactId>testing-runtime_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${testingVersion}</version>
        </dependency>
        <dependency>
            <groupId>com.sparkutils.</groupId>
            <artifactId>testing_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${testingVersion}</version>
            <scope>test</scope>
        </dependency>
        <!-- <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_${scalaCompatVersion}</artifactId>
            <version>${sparkVersion}</version>
            <scope>provided</scope>  
        </dependency> -->

        <dependency>
            <groupId>com.sparkutils</groupId>
            <artifactId>hadoop-bare-naked-local-fs</artifactId>
            <version>${naked-local-fs-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${guavaVersion}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.sparkutils</groupId>
            <artifactId>quality_server_shared_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${revision}</version>
            <exclusions> <!-- should not be included any way via shared -->
                <exclusion>
                    <groupId>com.sparkutils</groupId>
                    <artifactId>quality_api_stub_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scalaCompatVersion}</artifactId>
            <version>${sparkVersion}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-hive_${scalaCompatVersion}</artifactId>
            <version>${sparkVersion}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-avro_${scalaCompatVersion}</artifactId>
            <version>${sparkVersion}</version>
            <scope>test</scope>
        </dependency>

        <!-- added for parquets bloom -->
        <dependency>
            <groupId>net.openhft</groupId>
            <artifactId>zero-allocation-hashing</artifactId>
            <version>${zeroAllocHashingVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-rng-client-api</artifactId>
            <version>${rngVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-rng-core</artifactId>
            <version>${rngVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-rng-simple</artifactId>
            <version>${rngVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scalaVersion}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.scalatest</groupId>
            <artifactId>scalatest_${scalaCompatVersion}</artifactId>
            <version>${scalatestVersion}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>${framelessOrg}</groupId>
            <artifactId>frameless-dataset${framelessCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${framelessVersion}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sparkutils</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>${framelessOrg}</groupId>
            <artifactId>frameless-core${framelessCoreCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${framelessVersion}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sparkutils</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>${framelessOrg}</groupId>
            <artifactId>frameless-ml${framelessCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${framelessVersion}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sparkutils</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>${framelessOrg}</groupId>
            <artifactId>frameless-cats${framelessCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${framelessVersion}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sparkutils</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- only needed to compile frameless override in 10.4.dbr -->
        <dependency>
            <groupId>eu.timepit</groupId>
            <artifactId>refined_${scalaCompatVersion}</artifactId>
            <version>${refinedVersion}</version>
            <scope>provided</scope>
        </dependency>

        <!-- databricks runtime version is chosen to ease deployment there -->
        <dependency>
            <groupId>org.scala-lang.modules</groupId>
            <artifactId>scala-parser-combinators_${scalaCompatVersion}</artifactId>
            <version>${parserCombinatorVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-compiler</artifactId>
            <version>${scalaVersion}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.delta</groupId>
            <artifactId>delta-${deltaArtifact}_${scalaCompatVersion}</artifactId>
            <version>${deltaCoreVersion}</version>
            <scope>provided</scope> <!-- must be provided as there is no provided test, triggers antlr version issues -->
            <exclusions>
                <!-- let hive drive the version used, allows Spark 4 tests to run -->
                <exclusion>
                    <groupId>org.antlr</groupId>
                    <artifactId>antlr4-runtime</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.chuusai</groupId>
            <artifactId>shapeless_${scalaCompatVersion}</artifactId>
            <version>${shapelessVersion}</version>
        </dependency>

        <dependency>
            <groupId>${scalaMeterGroup}</groupId>
            <artifactId>${scalaMeterArtifact}_${scalaCompatVersion}</artifactId>
            <version>${scalaMeterVersion}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.mongodb</groupId>
                    <artifactId>casbah_${scalaCompatVersion}</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!--
        <dependency>
            <groupId>com.storm-enroute</groupId>
            <artifactId>scalameter_${scalaCompatVersion}</artifactId>
            <version>${scalaMeterVersion}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.mongodb</groupId>
                    <artifactId>casbah_${scalaCompatVersion}</artifactId>
                </exclusion>
            </exclusions>
        </dependency> -->

        <!-- needed for scalameter to run, no idea why it doesn't include it, also the version must be locked down -->
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-scala_${scalaCompatVersion}</artifactId>
            <version>${jacksonVersion}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jacksonVersion}</version>
            <scope>provided</scope>
        </dependency>

        <!-- Databricks packages this, oss does not -->
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>${snakeVersion}</version>
            <scope>${snakeScope}</scope>
        </dependency>

        <dependency>
            <groupId>org.scala-lang.modules</groupId>
            <artifactId>scala-collection-compat_${scalaCompatVersion}</artifactId>
            <version>${scalaCollectionCompatVersion}</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>${dependencyPluginVersion}</version>
                <executions> <!-- maven scala plugin uses a set to store classpath, it doesn't follow maven's so we need to use the source -->
                    <execution>
                        <id>unpack</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.sparkutils</groupId>
                                    <artifactId>shim_compilation_${shimCompilationRuntime}_${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
                                    <version>${shimCompilationVersion}</version>

                                    <classifier>sources</classifier>
                                    <type>jar</type>

                                    <overWrite>true</overWrite>
                                    <outputDirectory>${project.build.directory}/shim_compilation_${shimCompilationRuntime}_${sparkCompatVersion}_${scalaCompatVersion}</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.scalatest</groupId>
                <artifactId>scalatest-maven-plugin</artifactId>
                <version>${scalatestMavenPluginVersion}</version>
                <configuration>
                    <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
                    <junitxml>.</junitxml>
                    <filereports>WDF TestSuite.txt</filereports>
                    <!-- <htmlreporters>${project.build.directory}/html/scalatest</htmlreporters> -->
                    <argLine>-Xmx14g -ea -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED</argLine>
                </configuration>
                <executions>
                    <execution>
                        <id>test</id>
                        <goals>
                            <goal>test</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>
