@startuml

label 1 [
{{mindmap
<style>
mindmapDiagram {
  .passed {
    BackgroundColor lightgreen
  }
  .failed {
    BackgroundColor #FFBBCC
  }
  .softfailed {
    BackgroundColor lightblue
  }
  .different {
    font-weight bolder
  }
  fold {
    LineStyle 4
    LineThickness 0.5
    LineColor green
  }
}
</style>
*_ runner result column
 *_ ruleSuiteResults
  * Rule Suite - Id(1, 1)
  * overallResult == failed <<failed>>
  *_ ruleSetResults
   * Rule Set - Id(2, 1)
    * overallResult == failed <<failed>>
    *_ ruleResults
     * Rule - Id(3, 3) - failed <<failed>>
     * Rule - Id(4, 2) - *Salience 1000* - passed <<passed>>
   * Rule Set - Id(3, 2)
    * overallResult ==  passed <<passed>>
    *_ ruleResults
     * Rule - Id(5, 1) - soft failed <<softfailed>>
     * Rule - Id(6, 1) - *Salience 500* - passed <<passed>>
 * result (from below *folding*) <<fold>>
}}
{{
:sort all 'passed' Rule's Output Expressions by salience ascending Id(6,1) then Id(4,2);
:Use starting expression as <<output>>;
repeat
  :Call next Output Expression with <<output>> as it's input;
  :Use the result as <<output>>;
repeat while (More matching Output expressions?) is (yes) not (no)
:Use <<output>> as result;
}}
]
@enduml