package com.sparkutils.quality.impl.extension

object QualityVersionedRulesConstants {
  val QUALITY_VERSIONED: String = "QUALITY VERSIONED"
  val FROM_DF: String = "FROM DF "

  private def QUALITY_VERSIONED(what: String): String = s"$QUALITY_VERSIONED $what $FROM_DF"
  val QUALITY_VERSIONED_RULES_FROM_DF: String = QUALITY_VERSIONED("RULES")
  val QUALITY_VERSIONED_LAMBDAS_FROM_DF: String = QUALITY_VERSIONED("LAMBDAS")
  val QUALITY_VERSIONED_OUTPUT_EXPRESSIONS_FROM_DF: String = QUALITY_VERSIONED("OUTPUT EXPRESSIONS")
  val QUALITY_VERSIONED_RULESUITES_FROM_DF: String = QUALITY_VERSIONED("RULESUITES")
}
