@startmindmap

* Rule Suite - Id(1, 1) 
 *_ ruleSetResults
  * Rule Set - Id(2, 1)
   *_ ruleResults
    * Rule - Id(3, 3)
     *_ ruleResult - 124
     *_ resultType - BIGINT
    * Rule - Id(4, 2)
     *_ ruleResult - [5435, RESULT]
     *_ resultType - STRUCT<key: INT, value: STRING>
  * Rule Set - Id(3, 2)
   *_ ruleResults
    * Rule - Id(5, 1)
     *_ ruleResult - A Result
     *_ resultType - STRING
    * Rule - Id(6, 1)
     *_ ruleResult - 4304140.23414000
     *_ resultType - DECIMAL(20,18)

@endmindmap