package com.sparkutils.quality.impl

import com.sparkutils.quality.QualityException
import com.sparkutils.quality.impl.util.Params.formatParams
import com.sparkutils.quality.sparkless.impl.DecoderOpEncoderProjection
import com.sparkutils.quality.sparkless.impl.Processors.{NO_QUERY_PLANS, isCopyNeeded}
import org.apache.spark.sql.catalyst.InternalRow
import org.apache.spark.sql.{Encoder, QualitySparkUtils, ShimUtils}
import org.apache.spark.sql.catalyst.expressions.BindReferences.bindReferences
import org.apache.spark.sql.catalyst.expressions._
import org.apache.spark.sql.catalyst.expressions.aggregate.NoOp
import org.apache.spark.sql.catalyst.expressions.codegen.Block.BlockHelper
import org.apache.spark.sql.catalyst.expressions.codegen.{QualityExprUtils, JavaCode, _}
import org.apache.spark.sql.types.{DataType, StructField, StructType}

//import scala.collection.immutable.{Map, Seq}

/**
 * CODE is based on MutableProjection, but uses currentVars and wholestage elimination and generates a transformation between
 * two encoders over a middle operation.
 * The generated class itself can create new instances directly, unlike Spark projections that need to go through the
 * codegen source generation cycle, only the compilation is cached.
 *
 * If the expression tree contains stateful expressions with codegenfallback the code must be regenerated against a
 * fresh tree.
 */
object GenerateDecoderOpEncoderVarProjection extends CodeGenerator[Seq[Expression], DecoderOpEncoderProjection[_,_]] {

  // $COVERAGE-OFF$
  protected def bind(in: Seq[Expression], inputSchema: Seq[Attribute]): Seq[Expression] =
    bindReferences(in, inputSchema)
  protected def create(expressions: Seq[Expression]): DecoderOpEncoderProjection[_,_] = ???

  protected def canonicalize(in: Seq[Expression]): Seq[Expression] =
    in.map(ExpressionCanonicalizer.execute)
  // $COVERAGE-ON$


  // only for subexpresssion elimination, the tree is cleaned for statefuls on each new invocation, just not the first
  // one and freshCopyIfContainsStatefulExpression is also >3.4.1 only
  def generateExpressions(ctx: CodegenContext, expressions: Seq[Expression], subExprState: Map[ExpressionEquals,
    SubExprEliminationState]): Seq[ExprCode] =
    ctx.withSubExprEliminationExprs(subExprState)( expressions.toIndexedSeq.map(e => e.genCode(ctx) ) )

  def projections(ctx: CodegenContext, expressions: Seq[Expression], mutableRow: String,
                  subExprState: Map[ExpressionEquals, SubExprEliminationState] = Map.empty) = {
    val validExpr = expressions.zipWithIndex.filter {
      case (NoOp, _) => false
      case _ => true
    }

    val exprVals =
      generateExpressions(ctx, validExpr.map(_._1), subExprState).toIndexedSeq

    // 4-tuples: (code for projection, isNull variable name, value variable name, column index)
    val projectionCodes: Seq[(ExprCode, String, String)] = validExpr.zip(exprVals).map {
      case ((e, i), ev) =>
        val value = JavaCode.global(
          ctx.addMutableState(CodeGenerator.javaType(e.dataType), "value"),
          e.dataType)

        val (code, isNull) = if (e.nullable) {
          val isNull = ctx.addMutableState(CodeGenerator.JAVA_BOOLEAN, "isNull")
          (s"""
              |${ev.code}
              |$isNull = ${ev.isNull};
              |$value = ${ev.value};
            """.stripMargin, JavaCode.isNullGlobal(isNull))
        } else {
          (s"""
              |${ev.code}
              |$value = ${ev.value};
            """.stripMargin, FalseLiteral)
        }
        val expr = ExprCode(isNull, value)
        val update = CodeGenerator.updateColumn(
          mutableRow,
          e.dataType,
          i,
          expr,
          e.nullable)
        (expr, code, update)
    }
    projectionCodes
  }

  private def createVar(ctx: CodegenContext, f: DataType, rowName: String, i: Int): ExprCode = {
    val typ = JavaCode.javaType(f)

    val varName = ctx.freshName("decInput")
    val varNullName = ctx.freshName("decInput_isNull")
    ExprCode(code =
      code"""
          $typ $varName = ${CodeGenerator.getValue(rowName, f, i.toString)};
          boolean $varNullName = $rowName.isNullAt($i);
          """,
      JavaCode.variable(varNullName, classOf[Boolean]), JavaCode.variable(varName, f))
  }

  private def createVars(ctx: CodegenContext, struct: StructType, rowName: String): Seq[ExprCode] =
    struct.zipWithIndex.map { case (f, i) =>
      createVar(ctx, f.dataType, rowName, i)
    }

  // $COVERAGE-OFF$
  // for use in debugging rows generated by create's generated code
  def debug(row: InternalRow, any: Any): Unit = {
    println("here")
  }
  // $COVERAGE-ON$

  // directly taken from wholestage
  protected def evaluateVariables(variables: Seq[ExprCode]): String = {
    val evaluate = variables.filter(_.code.nonEmpty).map(_.code.toString).mkString("\n")
    variables.foreach(_.code = EmptyBlock)
    evaluate
  }

  protected def functions(ctx: CodegenContext, allExpr: Seq[String], paramsDef: String, paramsCall: String,
                          prefix: String): String = {
    val variablesPerFunc: Int = 40
    val variableFuncGroup: Int = 20 // defaults from rulerunner
    val grouped = allExpr.grouped(variablesPerFunc).grouped(variableFuncGroup)
    val funNames: Iterator[String] =
      RuleRunnerUtils.generateFunctionGroups(ctx, grouped, paramsDef, paramsCall, prefix = prefix)

    funNames.map { f => s"$f($paramsCall);" }.mkString("\n")
  }

  def create[I: Encoder, O: Encoder](expressions: Seq[Expression], toSize: Int,
                                     allOrdinals: Set[Int]): DecoderOpEncoderProjection[I,O] = {

    val iEnc = implicitly[Encoder[I]]
    //val oEnc = implicitly[Encoder[O]]
    val exprFrom = ShimUtils.expressionEncoder(iEnc).resolveAndBind().serializer
    val exprFromType = ShimUtils.expressionEncoder(iEnc).resolveAndBind().deserializer.dataType
    val exprTo = ShimUtils.expressionEncoder(implicitly[Encoder[O]]).resolveAndBind().deserializer

    if (expressions.exists(_.collect {
      case s: PlanExpression[_] => s
    }.nonEmpty)) {
      throw new QualityException(NO_QUERY_PLANS)
    }

    val cExpressions = canonicalize(expressions)

    val (resTypeIsStruct, resType) =
      if (toSize == 1)
        (cExpressions.last.dataType.isInstanceOf[StructType],
          cExpressions.last.dataType.asInstanceOf[StructType])
      else
        (false, null)

    val ctx = newCodeGenContext()

    ctx.INPUT_ROW = "enc"
    val input = ctx.freshName("_i_value")
    val nullInput = ctx.freshName("_i_isNull")
    val cast = JavaCode.boxedType(exprFromType)

    val topVarName = ctx.addMutableState(JavaCode.javaType(exprFromType).code, input, useFreshName = false)
    val topNullName = ctx.addMutableState("boolean", nullInput, useFreshName = false)
    val topVar: ExprCode = ExprCode(code =
      code"""
            $topVarName = ($cast) _i;
            $topNullName = $topVarName == null;
            """,
      JavaCode.variable(topNullName, classOf[Boolean]), JavaCode.variable(topVarName, iEnc.clsTag.runtimeClass))

    val topVarRef = Seq(topVar.copy(code = EmptyBlock))

    ctx.currentVars = topVarRef

    val nullLit = Literal(null)

    // only generate the actually used field mappings
    val fromExprs = exprFrom.zipWithIndex.map{
      case p if allOrdinals(p._2) => p._1
      case _ => nullLit // won't be used but needs to be present in the right order
    }

    val (encSubExprsCode, encSubExprInputs, encSubExprStates) =
      subElim(fromExprs, ctx)

    ctx.currentVars = encSubExprStates.map(_._2.eval).map(_.copy(code = EmptyBlock)).toIndexedSeq ++ topVarRef

    val encProjectionCodes = projections(ctx, exprFrom, "encRow", encSubExprStates).toIndexedSeq // streams suck

    // only generate the actually used field mappings
    val encProjectionCodesToUse = encProjectionCodes.zipWithIndex.collect{
      case p if allOrdinals(p._2) => p._1
    }

    val encProjections = functions(ctx, encProjectionCodesToUse.map(_._2), "InternalRow enc", "enc", "encoder")
    val encUpdates = functions(ctx, encProjectionCodesToUse.map(_._3), "InternalRow enc", "enc", "encoder")

    // need to keep all that may be used
    val exprVals = encProjectionCodes.map(_._1.copy(code = EmptyBlock))

    ctx.INPUT_ROW = "i"

    ctx.currentVars = exprVals ++ topVarRef

    val (projectionSubExprsCode, projectionSubExprInputs, projectionSubExprStates) =
      subElim(cExpressions, ctx)

    // we need InputRow to start with, after that we can bind to name
    ctx.currentVars = exprVals ++ projectionSubExprStates.map(_._2.eval).map(_.copy(code = EmptyBlock)) ++ topVarRef

    // generate the full set
    val projectionCodes = projections(ctx, cExpressions, "mutableRow", projectionSubExprStates).toIndexedSeq // streams suck

    val (projectionParamsDecl, projectionParamsCall) = formatParams( ctx, ctx.currentVars.flatMap(e => Seq(e.value, e.isNull)) :+
      JavaCode.variable(ctx.INPUT_ROW, classOf[InternalRow])
    )
    val (_, topProjectionParamsCall) = formatParams( ctx, ctx.currentVars.flatMap(e => Seq(e.value, e.isNull)) :+
      JavaCode.variable(ctx.INPUT_ROW, classOf[InternalRow]), callsKeepArrays = true
    )

    val allProjections = functions(ctx, projectionCodes.map(_._2), projectionParamsDecl, projectionParamsCall, "projection")

    // val allUpdates = projectionCodes.map(_._3).mkString("\n")

    val processorResult = projectionCodes.takeRight(toSize).map(_._1.value)

    // create vars for the interesting results
    val oexprVals = projectionCodes.drop( expressions.length - toSize).map(_._1.copy(code = EmptyBlock))

    val decSetupCodes =
      if (toSize == 1 && resTypeIsStruct)
        createVars(ctx, resType, oexprVals.head.value)
      else
        oexprVals

    val decSetupCode = ctx.splitExpressionsWithCurrentInputs(decSetupCodes.map(_.code.code))

    ctx.currentVars = decSetupCodes.map(_.copy(code = EmptyBlock))

    val (decSubExprsCode, decSubExprInputs, decSubExprStates) =
      subElim(Seq(exprTo), ctx)

    ///ctx.currentVars = null // it requires the vars to be provided for each input param
    ctx.INPUT_ROW = "dec"
    val (decParamsDecl, decParamsCall) = formatParams( ctx, ctx.currentVars.flatMap(e => Seq(e.value, e.isNull)) :+
      JavaCode.variable(ctx.INPUT_ROW, classOf[InternalRow])
    )
    val (_, topDecParamsCall) = formatParams( ctx, ctx.currentVars.flatMap(e => Seq(e.value, e.isNull)) :+
      JavaCode.variable(ctx.INPUT_ROW, classOf[InternalRow]), callsKeepArrays = true
    )

    val decProjectionCodes = projections(ctx, Seq(exprTo), "decRow", decSubExprStates).toIndexedSeq // streams suck

    val decProjections = functions(ctx, decProjectionCodes.map(_._2), decParamsDecl, decParamsCall, "decoding")

    val returnValue = decProjectionCodes.last._1.value

    val codeBody = s"""
      public java.lang.Object generate(Object[] references) {
        return new SpecificMutableProjection(references);
      }

      class SpecificMutableProjection extends ${classOf[DecoderOpEncoderProjection[I,O]].getName}<Object, Object> {

        private Object[] references;
        private InternalRow inRow;
        private InternalRow mutableRow;
        private InternalRow encRow;
        private InternalRow decRow;
        private InternalRow interim;
        ${ctx.declareMutableStates()}

        public SpecificMutableProjection(Object[] references) {
          this.references = references;
          mutableRow = new $genericMutableRowType(${expressions.size});
          inRow = new $genericMutableRowType(1);
          encRow = new $genericMutableRowType(${exprFrom.length});
          decRow = new $genericMutableRowType(${toSize});
          ${
            if (toSize == 1 && resTypeIsStruct)
              ""
            else
              s"interim = new $genericMutableRowType(${toSize});"
          }
          ${ctx.initMutableStates()}
        }

        public ${classOf[DecoderOpEncoderProjection[I,O]].getName} newInstance() {
          return new SpecificMutableProjection(references);
        }

        public void initialize(int partitionIndex) {
          ${ctx.initPartition()}
        }

        public void encode(InternalRow enc) {
          $encSubExprsCode

          // encoding from object done by subexprs
          $encProjections
          $encUpdates
        }

        public void projections($projectionParamsDecl){
          $allProjections
        }

        public void decode($decParamsDecl) {
          // dec subexprs setup
          ${evaluateVariables(decSubExprInputs)}
          // the code
          $decSubExprsCode

          // decoding projections
          $decProjections
        }

        //public ${implicitly[Encoder[O]].clsTag.runtimeClass.getName} apply(${implicitly[Encoder[I]].clsTag.runtimeClass.getName} _i) {
        public java.lang.Object apply(java.lang.Object _i) {
          inRow.update(0, _i);
          ${topVar.code}
          // input processing sub exprs need the enc
          InternalRow enc = (InternalRow) inRow;
          // the iterator isn't part of the wholestage so it gets the ctx level subexprs
          // enc sub setup
          ${evaluateVariables(encSubExprInputs)}
          // enc sub
          encode(enc);


          // may be in subexprs
          InternalRow i = (InternalRow) encRow;

          // common sub-expressions
          // setup
          ${evaluateVariables(projectionSubExprInputs)}
          // the code
          $projectionSubExprsCode

          // projections doing the actual work
          projections($topProjectionParamsCall);
          // copy all the results into MutableRow
          // allUpdates
          ${
            (for(i <- 1 to toSize) yield
              s"mutableRow.update(${expressions.size - i}, ${processorResult(toSize - i)});" // .copy() shouldn't be needed for row by row
              ).mkString("\n")
          }

          // uncomment to debug the output, extraProjection can introduce extra fields..
          // com.sparkutils.quality.impl.GenerateDecoderOpEncoderVarProjection.debug(mutableRow, $topVarName);

          // prepare input vars for the decoding
          $decSetupCode

          // prepare input row for decoding to end user type
          ${
            if (toSize == 1 && resTypeIsStruct)
              s"interim = mutableRow.getStruct(${expressions.length - 1}, ${resType.length});"
            else
              (for(i <- 0 until toSize) yield
                s"interim.update($i, ${CodeGenerator.getValue("mutableRow", expressions((expressions.length - toSize) + i).dataType, ((expressions.length - toSize) + i).toString)});"
                ).mkString("\n")
          }

          InternalRow dec = (InternalRow) interim;
          decode($topDecParamsCall);

          return /*(${implicitly[Encoder[O]].clsTag.runtimeClass.getName})*/ $returnValue;//decRow.get(0, new org.apache.spark.sql.types.ObjectType(Object.class));
        }


        ${ctx.declareAddedFunctions()}
      }
    """

    val code = CodeFormatter.stripOverlappingComments(
      new CodeAndComment(codeBody, ctx.getPlaceHolderToComments()))
    logDebug(s"code for ${expressions.mkString(",")}:\n${CodeFormatter.format(code)}")

    val (clazz, _) = CodeGenerator.compile(code)
    val initial = clazz.generate(ctx.references.toArray).asInstanceOf[DecoderOpEncoderProjection[I,O]]
    if (isCopyNeeded(expressions))
      new DecoderOpEncoderProjection[I,O] {

        override def apply(input: I): O = initial(input)

        // needs a fresh tree copy for each newInstance, so we need to proxy it
        override def newInstance: DecoderOpEncoderProjection[I, O] =
          create[I, O] ( expressions.map(e => e.transformUp { case t => t.withNewChildren(t.children) }),
            toSize, allOrdinals)

        override def initialize(partitionIndex: Int): Unit = initial.initialize(partitionIndex)
      }
    else
      // with no stateful CodegenFallback's the generated newInstance function is correct
      initial
  }

  private def subElim(exprFrom: Seq[Expression], ctx: CodegenContext) = {
    val subExprs = ctx.subexpressionEliminationForWholeStageCodegen(exprFrom)
    (ctx.evaluateSubExprEliminationState(subExprs.states.values), subExprs.exprCodesNeedEvaluate, subExprs.states)
  }
}
