<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>  <!-- rebuild -->


    <artifactId>quality_api_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
    <parent>
        <artifactId>quality_root_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
        <groupId>com.sparkutils</groupId>
        <version>${revision}</version>
    </parent>

    <version>${revision}</version>
    <name>Quality API</name>
    <description>Core connect compatible API for the Quality library</description>

    <profiles>
    </profiles>
    <properties>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.sparkutils</groupId>
            <artifactId>shim_runtime_${shimRuntime}_${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${shimRuntimeVersion}</version>
        </dependency>

        <dependency>
            <groupId>com.sparkutils</groupId>
            <artifactId>quality_api_stub_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${revision}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.sparkutils</groupId>
            <artifactId>quality_core_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scalaCompatVersion}</artifactId>
            <version>${sparkVersion}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-rng-simple</artifactId>
            <version>${rngVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scalaVersion}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>${framelessOrg}</groupId>
            <artifactId>frameless-dataset${framelessCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${framelessVersion}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sparkutils</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>${framelessOrg}</groupId>
            <artifactId>frameless-core${framelessCoreCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${framelessVersion}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sparkutils</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>${framelessOrg}</groupId>
            <artifactId>frameless-ml${framelessCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${framelessVersion}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sparkutils</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>${framelessOrg}</groupId>
            <artifactId>frameless-cats${framelessCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${framelessVersion}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sparkutils</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- only needed to compile frameless override in 10.4.dbr TODO - still needed? -->
        <dependency>
            <groupId>eu.timepit</groupId>
            <artifactId>refined_${scalaCompatVersion}</artifactId>
            <version>${refinedVersion}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.chuusai</groupId>
            <artifactId>shapeless_${scalaCompatVersion}</artifactId>
            <version>${shapelessVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.scala-lang.modules</groupId>
            <artifactId>scala-collection-compat_${scalaCompatVersion}</artifactId>
            <version>${scalaCollectionCompatVersion}</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>${dependencyPluginVersion}</version>
                <executions> <!-- maven scala plugin uses a set to store classpath, it doesn't follow maven's so we need to use the source -->
                    <execution>
                        <id>unpack</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.sparkutils</groupId>
                                    <artifactId>shim_compilation_${shimCompilationRuntime}_${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
                                    <version>${shimCompilationVersion}</version>

                                    <classifier>sources</classifier>
                                    <type>jar</type>

                                    <overWrite>true</overWrite>
                                    <outputDirectory>${project.build.directory}/shim_compilation_${shimCompilationRuntime}_${sparkCompatVersion}_${scalaCompatVersion}</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
