# Just runs docs from docs/test, simulates mvn setup
name: Docs only build

on:
  push:
    branches: [ "docs/test" ]

jobs:
  site:
    runs-on: ubuntu-latest

    steps:
      - uses: sparkutils/building/.github/workflows/docsOnly.yml@main
        with:
          profile: Spark4