# Only does a publish step, no tests are run
name: Publishes Only

on:
  push:
    branches: [ "publishOnly" ]

env:
  MAVEN_CLI_OPTS: &MAVEN_CLI_OPTS "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_CLI_TESTSHADES_OPTS: &MAVEN_CLI_TESTSHADES_OPTS "-f testShades/pom.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  # -Dmaven.repo.local=.m2/repository not needed on github, seems ~/.m2 is supported / expected
  MAVEN_OPTS_8: &MAVEN_OPTS_8 "-ea -XX:+IgnoreUnrecognizedVMOptions -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_OPTS_21: &MAVEN_OPTS_21 "-ea -XX:+IgnoreUnrecognizedVMOptions -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/sun.nio.cs=ALL-UNNAMED --add-opens java.base/sun.security.action=ALL-UNNAMED --add-opens java.base/sun.util.calendar=ALL-UNNAMED"

jobs:

  # only publish snapshots on main by default, or when ~cut-release is in the commits
  publish:
    needs: [ testBuilds_21, noTestBuilds_21, testBuilds, mvn_site, noTestBuilds ]
    uses: sparkutils/building/.github/workflows/publish_build.yml@main
    with:
      theMatrix: |
        {
          "profile": ["Spark3", "Spark32", "Spark321", "Spark313", "Spark332", "Spark341", "Spark350", "12.2.dbr", "13.1.dbr", "13.3.dbr", "14.0.dbr", "14.3.dbr", "15.4.dbr", "16.4.dbr"],
          "scala": [ "dummy" ]
        }
      jdk: 8
      mvnCliOpts: *MAVEN_CLI_OPTS
      mvnOpts: *MAVEN_OPTS_8
    secrets: inherit

  publishShadeBuilds:
    needs: [ publish ]
    uses: sparkutils/building/.github/workflows/publish_build.yml@main
    with:
      theMatrix: |
        {
          "profile": ["Spark3", "Spark32", "Spark321", "Spark313", "Spark332", "Spark341", "Spark350", "12.2.dbr", "13.1.dbr", "13.3.dbr", "14.0.dbr", "14.3.dbr", "15.4.dbr", "16.4.dbr"],
          "scala": [ "server" ]
        }
      jdk: 8
      mvnCliOpts: *MAVEN_CLI_TESTSHADES_OPTS
      mvnOpts: *MAVEN_OPTS_8
    secrets: inherit

  # all versions that can be built with tests - typically oss only.  Fail fast so we can see all compilation or test errors at once
  publishBuilds_21:
    needs: [ testBuilds_21, noTestBuilds_21, testBuilds, mvn_site, noTestBuilds ]
    uses: sparkutils/building/.github/workflows/publish_build.yml@main
    with:
      theMatrix: |
        {
          "profile": [ "Spark4", "17.3.dbr" ],
          "scala": [ "dummy" ]
        }
      jdk: 21
      mvnCliOpts: *MAVEN_CLI_OPTS
      mvnOpts: *MAVEN_OPTS_21
    secrets: inherit

  publishShadeBuilds_21:
    needs: [ publishBuilds_21 ]
    uses: sparkutils/building/.github/workflows/publish_build.yml@main
    with:
      theMatrix: |
        {
          "profile": [ "Spark4", "17.3.dbr" ],
          "scala": [ "server", "client" ]
        }
      jdk: 21
      mvnCliOpts: *MAVEN_CLI_TESTSHADES_OPTS
      mvnOpts: *MAVEN_OPTS_21
    secrets: inherit
